"""In-process figure store and Starlette route for side-channel trace delivery.

Trace data is serialised to JSON once (server-side, via Plotly's own encoder)
and served over a plain HTTP GET rather than through the Reflex WebSocket state
delta.  This avoids Reflex JSON-encoding millions of floats inside
``async with self`` and reduces the state-flush time from ~6 s to sub-100 ms.

The store is bounded to ``_MAX_TOKENS`` entries (FIFO eviction).  At ~31 MB
per figure the RSS ceiling is ~125 MB for the default of 4.
"""

from collections import OrderedDict

from plotly import graph_objects as go
from starlette.applications import Starlette
from starlette.requests import Request
from starlette.responses import Response
from starlette.routing import Route

_MAX_TOKENS = 4

# Keys are bare token strings (uuid4 hex).  Single-user dev deployment only;
# multi-session isolation would key on (client_token, sim_token).
_STORE: OrderedDict[str, bytes] = OrderedDict()


def put(token: str, fig: go.Figure) -> None:
    """Serialise *fig* to JSON bytes and store it under *token*.

    Evicts the oldest entry when the store exceeds ``_MAX_TOKENS``.

    Args:
        token: Short opaque identifier (uuid4 hex) generated by the caller.
        fig: Plotly figure to serialise.
    """
    _STORE[token] = fig.to_json().encode()
    while len(_STORE) > _MAX_TOKENS:
        _STORE.popitem(last=False)


def get_bytes(token: str) -> bytes:
    """Return the raw JSON bytes for *token*.

    Args:
        token: Token previously passed to :func:`put`.

    Returns:
        The JSON-encoded figure bytes as stored.

    Raises:
        KeyError: When *token* is not present in the store.
    """
    return _STORE[token]


async def _handle_figure(request: Request) -> Response:
    """Handle GET /api/figure/{token}.

    Args:
        request: Incoming Starlette request with ``token`` path param.

    Returns:
        HTTP 200 with JSON payload, or 404 when the token is unknown.
    """
    token = request.path_params["token"]
    try:
        data = get_bytes(token)
    except KeyError:
        return Response(content=b"figure token not found", status_code=404)
    return Response(content=data, media_type="application/json")


#: Starlette sub-application to mount via ``rx.App(api_transformer=...)``.
starlette_app = Starlette(
    routes=[Route("/api/figure/{token}", _handle_figure)],
)
