"""Integration tests for calcium-transient analysis with real simulations.

Verifies that :func:`analyze_calcium_transients_from_result` produces
sensible output when applied to traces generated by
:func:`simulate_current_clamp` for calcium-active presets, and that it
returns ``None`` for non-calcium neurons.  Unit tests with synthetic
traces live in tests/unit/test_calcium_transients.py.
"""

import dataclasses

import numpy as np

from patch_sim.analysis.calcium_transients import (
    analyze_calcium_transients_from_result,
)
from patch_sim.calcium import CalciumDynamics
from patch_sim.channels import GatingVariable, IonChannel, IonSpecies, NernstSpec
from patch_sim.clamp_simulations import simulate_current_clamp
from patch_sim.constants import PURKINJE
from patch_sim.neuron import Neuron
from patch_sim.presets import NEURON_PRESETS, make_squid_giant_axon
from patch_sim.protocols import step_current
from patch_sim.rates import VoltageOnlyFn


def _hh_with(*extras: IonChannel, **overrides: object) -> Neuron:
    """Build an HH52 squid neuron with the given extra channels appended."""
    base = make_squid_giant_axon()
    return dataclasses.replace(base, channels=base.channels + extras, **overrides)


# Mock calcium channel borrowed from the calcium simulation tests.
_CA_GATE = GatingVariable(
    name="ca_gate",
    power=1,
    alpha=VoltageOnlyFn(lambda _V, _ca_i: 0.1),
    beta=VoltageOnlyFn(lambda _V, _ca_i: 0.1),
)

_MOCK_CALCIUM_CHANNEL = IonChannel(
    name="mock_ca",
    g_max=1.0,
    gating_variables=(_CA_GATE,),
    reversal_spec=NernstSpec(IonSpecies.CALCIUM),
    carries_calcium=True,
)


def test_purkinje_preset_produces_calcium_transients() -> None:
    """Purkinje preset under strong current injection produces ≥1 transient.

    Purkinje is a tonic pacemaker with both ICaL and ICaT.  A moderate
    depolarising step drives high-frequency tonic firing and generates
    clear calcium transients.  We do not pin the exact count (it depends
    on integration details), only that the analysis recovers at least
    one transient with a peak above baseline.
    """
    neuron = NEURON_PRESETS[PURKINJE]()
    assert neuron.calcium_dynamics is not None

    protocol = step_current(
        duration=200.0,
        current_amplitude=10.0,
        step_start=10.0,
        step_duration=180.0,
    )
    result = simulate_current_clamp(neuron, protocol)
    assert result.dtype.names is not None
    assert "ca_i" in result.dtype.names

    analysis = analyze_calcium_transients_from_result(result)
    assert analysis is not None
    assert analysis.transient_count >= 1
    assert analysis.mean_peak_concentration is not None
    assert analysis.baseline_concentration is not None
    assert analysis.mean_peak_concentration > analysis.baseline_concentration


def test_classic_hh_returns_none(hh_model: Neuron) -> None:
    """A classic HH neuron without calcium dynamics yields ``None``.

    The ``hh_model`` fixture has ``calcium_dynamics=None`` and the
    simulation result has no ``ca_i`` field — the wrapper must
    short-circuit to ``None``.

    Args:
        hh_model: Classic Hodgkin–Huxley neuron fixture (no calcium dynamics).
    """
    assert hh_model.calcium_dynamics is None
    protocol = step_current(
        duration=20.0,
        current_amplitude=10.0,
        step_start=2.0,
        step_duration=15.0,
    )
    result = simulate_current_clamp(hh_model, protocol)
    assert result.dtype.names is not None
    assert "ca_i" not in result.dtype.names

    assert analyze_calcium_transients_from_result(result) is None


def test_mock_ca_channel_step_produces_recoverable_transient() -> None:
    """A depolarising step on a Ca-channel-only neuron yields one transient.

    The mock-Ca neuron has a single Ca²⁺-permeable channel with a slow
    (10 ms) gate.  A 50 ms depolarising step opens the gate, drives an
    inward Ca²⁺ flux that ramps ca_i up; when the step ends the Ca²⁺
    concentration relaxes back toward ``ca_rest`` with the configured
    ``tau_ca``.  The analysis should recover a single transient whose
    decay τ is in the same order of magnitude as ``tau_ca``.
    """
    cd = CalciumDynamics(alpha_ca=1e-3, tau_ca=200.0, ca_rest=1e-4)
    neuron = _hh_with(_MOCK_CALCIUM_CHANNEL, calcium_dynamics=cd)
    protocol = step_current(
        duration=600.0,
        current_amplitude=0.0,
        step_start=50.0,
        step_duration=50.0,
    )
    result = simulate_current_clamp(neuron, protocol)
    analysis = analyze_calcium_transients_from_result(result)
    assert analysis is not None
    assert analysis.transient_count >= 1
    transient = analysis.transients[0]
    assert transient.peak_concentration > transient.baseline_concentration
    # The macroscopic decay τ is shaped by both tau_ca and gate closure;
    # it is bounded above by tau_ca but may be considerably faster, so we
    # only check positivity / finiteness here.
    if transient.decay_tau is not None:
        assert np.isfinite(transient.decay_tau) and transient.decay_tau > 0.0
