"""Ion channel subpackage for the conductance-based neuron simulator.

Re-exports the base channel types and all factory functions so external callers
can import from ``patch_sim.channels`` (or ``patch_sim``) without knowing the
internal submodule layout.
"""

from .auxiliary import (
    make_ical_channel,
    make_ican_channel,
    make_icat_channel,
    make_ih_channel,
    make_ika_channel,
    make_ikca_channel,
    make_ikir_channel,
    make_ikv31_channel,
    make_im_channel,
    make_inap_channel,
    make_inar_channel,
    make_katp_channel,
    make_sk_channel,
)
from .base import (
    _CA_NERNST_FLOOR,
    GatingVariable,
    GoldmanSpec,
    IonChannel,
    IonSpecies,
    NernstSpec,
    ReversalSpec,
)
from .hh52 import (
    SINGULARITY_THRESHOLD,
    alpha_h,
    alpha_m,
    alpha_n,
    beta_h,
    beta_m,
    beta_n,
    make_k_channel,
    make_k_leak_channel,
    make_na_channel,
    make_na_leak_channel,
)
from .mainen_sejnowski import (
    MAINEN_SEJNOWSKI_KV_PRESCALE,
    MAINEN_SEJNOWSKI_KV_VHALF,
    MAINEN_SEJNOWSKI_NA_THA,
    mainen_sejnowski_alpha_h,
    mainen_sejnowski_alpha_m,
    mainen_sejnowski_alpha_n,
    mainen_sejnowski_beta_h,
    mainen_sejnowski_beta_m,
    mainen_sejnowski_beta_n,
    make_mainen_sejnowski_kv_channel,
    make_mainen_sejnowski_na_channel,
)
from .pospischil import (
    POSPISCHIL_VT,
    make_nav11_channel,
    make_nav12_channel,
    make_pospischil_k_channel,
    pospischil_alpha_h,
    pospischil_alpha_m,
    pospischil_alpha_n,
    pospischil_beta_h,
    pospischil_beta_m,
    pospischil_beta_n,
)
from .purkinje import (
    PURKINJE_VT,
    make_purkinje_k_channel,
    make_purkinje_na_channel,
    purkinje_alpha_h,
    purkinje_alpha_m,
    purkinje_alpha_n,
    purkinje_beta_h,
    purkinje_beta_m,
    purkinje_beta_n,
)
from .snc import (
    DOPAMINERGIC_VT,
    dopaminergic_alpha_h,
    dopaminergic_alpha_m,
    dopaminergic_alpha_n,
    dopaminergic_beta_h,
    dopaminergic_beta_m,
    dopaminergic_beta_n,
    make_cav13_channel,
    make_dopaminergic_k_channel,
    make_dopaminergic_na_channel,
    make_snc_inap_channel,
)
from .stn import (
    make_stn_k_channel,
    make_stn_na_channel,
)
from .thalamic import (
    THALAMIC_RELAY_VT,
    make_thalamic_relay_icat_channel,
    make_thalamic_relay_k_channel,
    make_thalamic_relay_na_channel,
    thalamic_relay_alpha_h,
    thalamic_relay_alpha_m,
    thalamic_relay_alpha_n,
    thalamic_relay_beta_h,
    thalamic_relay_beta_m,
    thalamic_relay_beta_n,
)
from .trn import (
    TRN_VT,
    make_trn_icat_channel,
    make_trn_k_channel,
    make_trn_na_channel,
    trn_alpha_h,
    trn_alpha_m,
    trn_alpha_n,
    trn_beta_h,
    trn_beta_m,
    trn_beta_n,
)

__all__ = [
    # base types
    "GatingVariable",
    "GoldmanSpec",
    "IonChannel",
    "IonSpecies",
    "NernstSpec",
    "ReversalSpec",
    "_CA_NERNST_FLOOR",
    # hh52
    "SINGULARITY_THRESHOLD",
    "alpha_h",
    "alpha_m",
    "alpha_n",
    "beta_h",
    "beta_m",
    "beta_n",
    "make_k_channel",
    "make_k_leak_channel",
    "make_na_channel",
    "make_na_leak_channel",
    # pospischil
    "POSPISCHIL_VT",
    "make_nav11_channel",
    "make_nav12_channel",
    "make_pospischil_k_channel",
    "pospischil_alpha_h",
    "pospischil_alpha_m",
    "pospischil_alpha_n",
    "pospischil_beta_h",
    "pospischil_beta_m",
    "pospischil_beta_n",
    # mainen_sejnowski
    "MAINEN_SEJNOWSKI_KV_PRESCALE",
    "MAINEN_SEJNOWSKI_KV_VHALF",
    "MAINEN_SEJNOWSKI_NA_THA",
    "mainen_sejnowski_alpha_h",
    "mainen_sejnowski_alpha_m",
    "mainen_sejnowski_alpha_n",
    "mainen_sejnowski_beta_h",
    "mainen_sejnowski_beta_m",
    "mainen_sejnowski_beta_n",
    "make_mainen_sejnowski_kv_channel",
    "make_mainen_sejnowski_na_channel",
    # auxiliary
    "make_ical_channel",
    "make_ican_channel",
    "make_icat_channel",
    "make_ih_channel",
    "make_ika_channel",
    "make_ikca_channel",
    "make_ikir_channel",
    "make_ikv31_channel",
    "make_im_channel",
    "make_inap_channel",
    "make_inar_channel",
    "make_katp_channel",
    "make_sk_channel",
    # thalamic
    "THALAMIC_RELAY_VT",
    "make_thalamic_relay_icat_channel",
    "make_thalamic_relay_k_channel",
    "make_thalamic_relay_na_channel",
    "thalamic_relay_alpha_h",
    "thalamic_relay_alpha_m",
    "thalamic_relay_alpha_n",
    "thalamic_relay_beta_h",
    "thalamic_relay_beta_m",
    "thalamic_relay_beta_n",
    # trn
    "TRN_VT",
    "make_trn_icat_channel",
    "make_trn_k_channel",
    "make_trn_na_channel",
    "trn_alpha_h",
    "trn_alpha_m",
    "trn_alpha_n",
    "trn_beta_h",
    "trn_beta_m",
    "trn_beta_n",
    # purkinje
    "PURKINJE_VT",
    "make_purkinje_k_channel",
    "make_purkinje_na_channel",
    "purkinje_alpha_h",
    "purkinje_alpha_m",
    "purkinje_alpha_n",
    "purkinje_beta_h",
    "purkinje_beta_m",
    "purkinje_beta_n",
    # stn
    "make_stn_k_channel",
    "make_stn_na_channel",
    # snc
    "DOPAMINERGIC_VT",
    "dopaminergic_alpha_h",
    "dopaminergic_alpha_m",
    "dopaminergic_alpha_n",
    "dopaminergic_beta_h",
    "dopaminergic_beta_m",
    "dopaminergic_beta_n",
    "make_cav13_channel",
    "make_dopaminergic_k_channel",
    "make_dopaminergic_na_channel",
    "make_snc_inap_channel",
]
